### ISSUE TITLE
Browser Compatibility Matrix

### ISSUE THREAD

**Issue by solojavier** [adobe/aem-core-cif-components#11]
Could you please provide what browsers are supported to know where can we tests and report any issues we may find?

It's also helpful to understand the gap for the browsers we need to support in a project.

**Comment by herzog31** [comment]
Hi @solojavier,

our components will have dependencies to [Magento PWA Studio](https://github.com/magento-research/pwa-studio) and React. For those projects, the browser support is fluid and defined during build time. For PWA Studio, you can find the currently supported browsers defined in https://github.com/magento-research/pwa-studio/blob/master/browserslist.js. 

For our project, we will follow the approach of using [browserslist](https://github.com/browserslist/browserslist) and try to not further restrict the supported browsers.
