### ISSUE TITLE
Question: Roadmap

### ISSUE THREAD

**Issue by robertymb** [adobe/aem-core-cif-components#118]
Hi there,

Do you have a roadmap to deliver features for AEM Core CIF Components?

Thanks,

**Comment by mhaack** [comment]
Yes we have and it is shared regularly in our CIF Update events. And today is your lucky day since the next update is today: https://digitalu.adobe.com/events.event.html/aem-magento_integrat-3SrH.html

So far the roadmap is not published here. @aditidc what do you think?

**Comment by shamrox** [comment]
> Yes we have and it is shared regularly in our CIF Update events. And today is your lucky day since the next update is today: https://digitalu.adobe.com/events.event.html/aem-magento_integrat-3SrH.html
> 
> So far the roadmap is not published here. @aditidc what do you think?

How do I get access to that link?

**Comment by aditidc** [comment]
Our latest webinar was on 12/05. Do you have access to Solution Partner Portal?https://solutionpartners.adobe.com/home/hp/learn/partner_webinar.html You can access the recording in this link. Regarding the roadmap, we don't publish it. Is there anything specific you were looking for?
