### ISSUE TITLE
Documentation for categoryRootId

### ISSUE THREAD

**Issue by solojavier** [adobe/aem-core-cif-components#13]
Currently there is a manual step that needs to be performed for categories to work, but it's not documented anywhere:

> Go to http://localhost:4502/crx/de/index.jsp#/content/venia/us/en/products/jcr%3Acontent there is magentoRootCategoryId property, that should be your Magento Default Category, same like used for binding.

**Comment by mhaack** [comment]
We have already #10 open to address this and other documentation issues.
