### ISSUE TITLE
Build requires npm to be installed

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-core-cif-components#156]
The maven build of the reactor breaks if no npm binary is installed. This could be avoided if the maven-frontend-plugin is used, which allows to freely specify which version of node and npm should be used.
It also makes it easier to build the project without maintaining these dependencies manually.

**Comment by dplaton** [comment]
Thanks for pointing this out, @joerghoh. We'll start investigating this soon.

**Comment by cjelger** [comment]
PR for this issue: https://github.com/adobe/aem-core-cif-components/pull/182
