### ISSUE TITLE
Feature request: Data Layer capability

### ISSUE THREAD

**Issue by retozigerlig** [adobe/aem-core-cif-components#196]
### User Story
As a Analytics consultant I would like to be able to track the whole commerce flow in a standardised way without the need of code changes on component/template level.
### Description & Motivation
Is it planned to add Data Layer capability to the CIF Core Components? If so, when will this be available?
### Deliverables
tbd
### Acceptance Criteria
tbd
### Verification Steps
tbd

**Comment by mhaack** [comment]
@retozigerlig yes that is planed and we will add Data Layer capabilities as well. I let @aditidc comment on the roadmap.
You are also free to add it and create a PR :-)

**Comment by retozigerlig** [comment]
Thanks for your reply @mhaack . Where can I find the mentioned roadmap?

**Comment by creatorpiyush** [comment]
Can I take this issue if no one is working on it?

**Comment by herzog31** [comment]
@creatorpiyush feel free to submit a PR :)

**Comment by cjelger** [comment]
This was added by https://github.com/adobe/aem-core-cif-components/pull/415
