### ISSUE TITLE
Feature Request: Allow dynamic filtering of search results

### ISSUE THREAD

**Issue by kevin-mitchell** [adobe/aem-core-cif-components#198]
### User Story
As a user I want to able to use the filtering or "faceting" functionality provided by Magento to more easily narrow down search results.

### Description & Motivation

Magento allows for dynamic filtering of search results based on attribute configuration within Magento. It would be nice if the search related components supported some of this functionality. The "dynamic" part of this comes in because the attributes that are configured for search within Magento are dynamic and so too the AEM components used should also be dynamic so that as the searchable attributes are updated in Magento the attributes too are updated within AEM.

### Deliverables

* Additional components
* Modification to existing search, navigation bar, and potentially product list UI elements
* Ability to make simple introspection queries is required to be able to dynamically query Magento's GraphQL endpoints

### Acceptance Criteria

_After setting up CIF and adding the appropriate search component(s) to a page..._

* Search displays with a list of available filters
* Adding a new attribute as filterable in Magento should result in the option being available for filtering in AEM
* Removing an attribute from Magento should also remove the attribute as a filter option from the AEM search steps

**Comment by mhaack** [comment]
Fixed by #223

**Comment by mhaack** [comment]
Thanks for contributing @kevin-mitchell
