### ISSUE TITLE
mvn clean install is giving error

### ISSUE THREAD

**Issue by vidyaav** [adobe/aem-core-cif-components#235]
### Expected Behaviour
Project compiles succesfully
### Actual Behaviour
Getting error "MagentoGraphqlClient.java has not been previously formatted.  Please format file and commit before running validation!"
### Reproduce Scenario (including but not limited to)
Download zip file, extract, run mvn clean install
#### Steps to Reproduce
Download zip file, extract, run mvn clean install
#### Platform and Version
master version
#### Logs taken while reproducing problem

**Comment by deepkamal** [comment]
Code formatting is automatically checked during the Maven verify phase. To automatically format your code, run `mvn clean install -Pformat-code`.

refer: [Pull 44](https://github.com/adobe/aem-core-cif-components/pull/44)

**Comment by vidyaav** [comment]
Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.0.24 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @

This is what I'm getting if I run the command, Is there any dependency I need to add in pom file or in settings.xml for it to pick up that profile?

**Comment by mhaack** [comment]
Please see here: https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html ... for all AEM projects, not special to CIF.
