### ISSUE TITLE
cart not updating

### ISSUE THREAD

**Issue by dabe5651** [adobe/aem-core-cif-components#283]
### Expected Behaviour
1. When a user enters shipping address the tax is updated.
2. When a user selects a shipping method, the shipping cost is updated
### Actual Behaviour
Neither get updated until page is reloaded .
#### Platform and Version
AEM 6.5.0
Magento 2.3.4
CIF 1.0.1
#### Logs taken while reproducing problem

**Comment by dabe5651** [comment]
PR opened https://github.com/adobe/aem-core-cif-components/pull/284

**Comment by herzog31** [comment]
Fixed by #284. Thanks for your contribution!
