### ISSUE TITLE
FilterRangeTypeInput doesn't account for *_????

### ISSUE THREAD

**Issue by shamrox** [adobe/aem-core-cif-components#286]
### Expected Behaviour
When you filter on price for *_10 you should get a result back of all products from 0_10.

### Actual Behaviour
When you filter for *_10 no items are returned because it is passing a * in from price

### Reproduce Scenario (including but not limited to)
Add product listing to category page.

#### Steps to Reproduce
Click the first filter *_10
Page reloads and no items found

#### Platform and Version
AEM 6.5.3
Magento 6.4.3

#### Sample Code that illustrates the problem

```
filter.setFrom(rangeValues[0]);
// For values such as `60_*`, the to range should be left empty
if (StringUtils.isNumeric(rangeValues[1])) {
    filter.setTo(rangeValues[1]);
}
```

**Comment by herzog31** [comment]
Fixed by #308.
