### ISSUE TITLE
My account dropdown - move the Sign in option in the dropdown

### ISSUE THREAD

**Issue by dplaton** [adobe/aem-core-cif-components#303]
### User Story
As a visitor, I want to have a dedicated space from which I can access "Sign in" options, without having to open the navigation side panel. 

### Deliverables
1. Updated Header component with the icon for the user dropdown
2. The drop-down containing only the sign-in button, with complete functionality (enter username and password, sign in)
4. The sign-out option must be accessible and functional
3. After the sign in the dropdown will only display the user name and the sign-out option.

### Acceptance Criteria

1. The feature is implemented
2. The unit tests meet the coverage criteria
3. The UI fits the Venia theme

### Verification Steps
1. Create a new project using the archetype
2. Install the SNAPSHOT version of this project.
3. Check the home page:
1.1 The user icon must be present in the header component
1.2 Clicking the icon opens the dropdown which has the sign-in form
1.3 Enter an existing username and password and click "Sign in" - the user should be signed in and the "Sign out" button should be displayed
1.4 Click the "Sign out" option. It should work as expected.

### Mockups:
Before logging in: 

- we should keep the "Sign in" text next to the icon
<img width="527" alt="Screenshot 2020-06-23 at 10 34 33" src="https://user-images.githubusercontent.com/1407821/85374392-61ffad80-b53d-11ea-9876-b0f875e90662.png">

- after login, dropdown closed

<img width="428" alt="Screenshot 2020-06-23 at 10 34 54" src="https://user-images.githubusercontent.com/1407821/85374404-64fa9e00-b53d-11ea-9f75-f92012a29e3b.png">

- dropdown open
- we don't need all the links here, but we should at least have "Account information" and "Address Book"
<img width="467" alt="Screenshot 2020-06-23 at 10 35 13" src="https://user-images.githubusercontent.com/1407821/85374407-65933480-b53d-11ea-8dcc-bd2f8c5ca111.png">

### Internal ref
CIF-1444 and CIF-1445

**Comment by mhaack** [comment]
Issue resolved and verified.
