### ISSUE TITLE
The price search facet does not work when the price is a single value

### ISSUE THREAD

**Issue by okassa-241** [adobe/aem-core-cif-components#317]
### Expected Behaviour

**Given :** As a visitor on the venia website
**When :**  i click on the price search face
**And :** my price facet value is a single value (30 and not a range 20_30)
**Then :** I expected the venia website to display all the product in the current categoy
which have 30$ as price

### Actual Behaviour

**Given :** As a visitor on the venia website
**When :**  i click on the price search face
**And :** my price facet value is a single value (30 and not a range 20_30)
**Then :** I do not see any product displayed 

### Reproduce Scenario (including but not limited to)

- Configure a Magento instance to display all price aggregates from a category with single values and not a ranges.
- Configure the CIF with AEM (author,publish) as per the official documentation
- Open a category page and check the values of the price facet

#### Platform and Version

AEM 6.5
Magento 2.3.4

#### Sample Code that illustrates the problem
GraphQL query executed by the CIF
`{
  products(currentPage: 1, pageSize: 6, filter: {category_id: {eq: "8"}}) {
    total_count
    items {
      __typename
      id
      sku
      name
      small_image {
        url
      }
      url_key
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
          final_price {
            value
            currency
          }
          discount {
            amount_off
            percent_off
          }
        }
      }
      ... on ConfigurableProduct {
        price_range {
          maximum_price {
            regular_price {
              value
              currency
            }
            final_price {
              value
              currency
            }
            discount {
              amount_off
              percent_off
            }
          }
        }
      }
    }
    aggregations {
      options {
        count
        label
        value
      }
      attribute_code
      count
      label
    }
  }
}
`

Price aggregates with single values
`        "aggregations": [
        {
          "options": [
            {
              "count": 1,
              "label": "34",
              "value": "34"
            },
            {
              "count": 1,
              "label": "100",
              "value": "100"
            }
          ],
          "attribute_code": "price",
          "count": 2,
          "label": "Price"
        }
 ]`

Price aggregates with ranges
`"aggregations": [
        {
          "options": [
            {
              "count": 1,
              "label": "10-20",
              "value": "10_20"
            },
            {
              "count": 6,
              "label": "20-30",
              "value": "20_30"
            },
            {
              "count": 6,
              "label": "30-40",
              "value": "30_40"
            },
            {
              "count": 7,
              "label": "40-50",
              "value": "40_50"
            },
            {
              "count": 6,
              "label": "50-60",
              "value": "50_60"
            },
            {
              "count": 2,
              "label": "60-70",
              "value": "60_70"
            },
            {
              "count": 1,
              "label": "70-80",
              "value": "70_80"
            },
            {
              "count": 1,
              "label": "80-90",
              "value": "80_90"
            },
            {
              "count": 2,
              "label": "90-*",
              "value": "90_*"
            }
          ],
          "attribute_code": "price",
          "count": 9,
          "label": "Price"
        }
]`
#### Logs taken while reproducing problem

**Comment by cjelger** [comment]
Fixed by #329
