### ISSUE TITLE
Add to Cart Not Working

### ISSUE THREAD

**Issue by jasonmadisonperficient** [adobe/aem-core-cif-components#321]
### Expected Behaviour
Product is added to cart.

### Actual Behaviour
Dispatcher Docker log shows DNS error.
[Fri Jun 26 03:26:36.020909 2020] [proxy:error] [pid 7:tid 140345463514880] [client 172.17.0.1:59964] AH00898: DNS lookup failure for: magento235hv.local returned by /magento/graphql, referer: http://localhost/content/venia/us/en/products/product-page.affirm-water-bottle.html
172.17.0.1 - - [26/Jun/2020:03:26:26 +0000] "POST /magento/graphql HTTP/1.1" 502 351

### Reproduce Scenario (including but not limited to)
AEM 6.5 running on local host machine.
Magento 2.3.5 running on Hyper-V via Vagrant.
AEM Dispatcher Docker running as described here.

#### Steps to Reproduce
Access PDP which loads fine.
Add to Cart button appears to be working, but error received after fetching cart data for a while.

#### Platform and Version
AEM 6.5 running on local host machine.
Magento 2.3.5 running on Hyper-V via Vagrant.
AEM Dispatcher Docker running as described here.

#### Sample Code that illustrates the problem
See above.

#### Logs taken while reproducing problem
Docker logs pasted above.

**Comment by herzog31** [comment]
The error log indicates a misconfiguration of the dispatcher. If you configure the dispatcher inside Docker, make sure to use a hostname / IP that is available inside the container. Ideally you use the host IP of the machine Magento runs on. You can use `docker exec` to run a ping or curl command inside your container to validate your configuration.

**Comment by jasonmadisonperficient** [comment]
Thank you @herzog31 
I was able to resolve this by forcing all VMs to use 192.168.200.0/28.
Much appreciate the quick help!
