### ISSUE TITLE
[Bundle products] Implement option and quantity selection

### ISSUE THREAD

**Issue by cjelger** [adobe/aem-core-cif-components#328]
### User Story
As a user, I want to be able to select the options and quantities of the items of a bundle product. When selecting an option and/or changing the selected quantities, the price calculation and bundle content should be updated to always display the current selection. See the screenshot of that feature in Magento's LUMA demo.

### Deliverables
That feature should be implemented client-side as a React component. The selection of options and quantities should be stored so that's later possible to add the bundle product to the cart but this will be implemented in another related issue. This will done according to https://devdocs.magento.com/guides/v2.3/graphql/mutations/add-bundle-products.html

The content and options of the bundle product should be fetched client-side with GraphQL, using the `onBundleProduct` fragment of a product query.

### Acceptance Criteria
The user must be able to select the option(s) and quantities of the bundle product, and the price and current content of the bundle must always be displayed. upon changes.

### Screenshots
![Screenshot 2020-07-06 at 11 28 55](https://user-images.githubusercontent.com/24548615/86578346-f6c1cc80-bf7b-11ea-99ab-3a19b525f0e0.png)

**Comment by LSantha** [comment]
Resolved with https://github.com/adobe/aem-cif-guides-venia/pull/39 .
