### ISSUE TITLE
Product added to cart and removes on the page load - cookie not set

### ISSUE THREAD

**Issue by bharathkeystride** [adobe/aem-core-cif-components#333]
### Expected Behaviour

1. When user add product to cart, it is added.
2. When user refresh the page or navigate to any other page, the added product stays in cart.

### Actual Behaviour

Product removes from cart if navigate to other page or we reload the page.
The cookie 'cif.cart' is not set

#### Platform and Version
AEM 6.5.0
Magento 2.3.4
CIF 1.1.0
#### Logs taken while reproducing problem

**Comment by herzog31** [comment]
@bharathkeystride can you please check if the issue is solved with the latest version? I suspect the issue occurred because of https://github.com/adobe/aem-core-cif-components/pull/389.
