### ISSUE TITLE
Use an address from the Address Book during checkout

### ISSUE THREAD

**Issue by dplaton** [adobe/aem-core-cif-components#362]
### User Story

As a registered shopper, I want to select an address from my address book during checkout.

### Description & Motivation

During the checkout experience, a registered shopper must be able to select an address from the address book as the shipping or billing address

### Deliverables

* A dropdown has to be added to the shipping and billing address steps of the checkout experience
* The values in the dropdown should be the street names
* The dropdown and the address form should be pre-filled with the default address

### Acceptance Criteria

* In the "Shipping Address" section I have the form pre-filled with my default address. I also have a dropdown that lists the addresses (street names) that I can choose another address from.
* In the "Billing address" section - if I deselect the "Same as shipping address" option I get the address form and a dropdown from which I can select a different address

**Comment by LSantha** [comment]
Resolved with https://github.com/adobe/aem-core-cif-components/pull/375 .
