### ISSUE TITLE
JavaScript errors on Product pages if Product can't be found

### ISSUE THREAD

**Issue by dhardtke** [adobe/aem-core-cif-components#369]
### Expected Behaviour
When opening a product page where the product can't be found, the Product component should not throw.

### Actual Behaviour
![Screenshot_20200810_125119](https://user-images.githubusercontent.com/1360135/89775500-34c88800-db08-11ea-96a0-b8281256ae15.png)
When loading the page (e.g. http://localhost:4502/content/venia/us/en/products/product-page.i-do-not-exist.html) a JS error appears in the console.

### Reproduce Scenario (including but not limited to)
Open a product detail page where the product can't be found.

#### Steps to Reproduce
1. Open http://localhost:4502/content/venia/us/en/products/product-page.i-do-not-exist.html
2. Notice the error in the console (see the screenshot above)

#### Platform and Version
AEM 6.5.5 on-premise, CIF Components 1.2.0

#### Sample Code that illustrates the problem
-

#### Logs taken while reproducing problem
-

**Comment by herzog31** [comment]
Fixed by #370.
