### ISSUE TITLE
Idea for improved Customization of Product Teaser component when teasing variants

### ISSUE THREAD

**Issue by dhardtke** [adobe/aem-core-cif-components#372]
### Expected Behaviour
See Sample Code

### Actual Behaviour
See Sample Code

#### Platform and Version
Core CIF Components 1.2.0
AEM 6.5.0

#### Sample Code that illustrates the problem
Using delegation, I can customize the `ProductTeaser` comp with ease (e.g. add a `getCountryOfManufacture` method):

```java
@Model(adaptables = SlingHttpServletRequest.class, adapters = MyProductTeaser.class, resourceType = MyProductTeaserImpl.RESOURCE_TYPE)
public class MyProductTeaserImpl implements MyProductTeaser {

    protected static final String RESOURCE_TYPE = "shop/components/commerce/productteaser";

    @Self
    @Via(type = ResourceSuperType.class)
    private ProductTeaser productTeaser;

    private AbstractProductRetriever productRetriever;

    @PostConstruct
    public void initModel() {
        productRetriever = productTeaser.getProductRetriever();

        if (productRetriever != null) {
            productRetriever.extendProductQueryWith(p -> p.countryOfManufacture());
        }
    }

    @Override
    public String getCountryOfManufacture() {
        return productRetriever.fetchProduct().getCountryOfManufacture();
    }

    @Override
    public String getFormattedPrice() {
        return productTeaser.getPriceRange().getFormattedFinalPrice();
    }

    @Override
    public Price getPriceRange() {
        return productTeaser.getPriceRange();
    }

    @Override
    public String getImage() {
        return productTeaser.getImage();
    }

    @Override
    public String getName() {
        return productTeaser.getName();
    }

    @Override
    public String getUrl() {
        return productTeaser.getUrl();
    }

    @Override
    public String getSku() {
        return productTeaser.getSku();
    }

    @Override
    public String getCallToAction() {
        return productTeaser.getCallToAction();
    }

    @Override
    public Boolean isVirtualProduct() {
        return productTeaser.isVirtualProduct();
    }

    @Override
    public AbstractProductRetriever getProductRetriever() {
        return productRetriever;
    }
}
```
This works fine for base variants (e.g. `WJ08`), but it doesn't for sub-variants (e.g. `WJ08-XS-Gray`) because the `ProductRetriever` is given only the left side of the SKU (see https://github.com/adobe/aem-core-cif-components/blob/5bd20356c1d1bb2b5d58dbe4b552c76a326963d9/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java#L98). `ProductRetriever#fetchProduct` will always return the base variant.

Unfortunately, getProduct() of the impl class is `private`. Is there a reason, the `ProductTeaser` explicitly passes only the LHS of the SKU to the `ProductRetriever`?

I'd at least wish it was configurable in some way. Or, if it was a design decision, prevent editors from choosing a variant of a SKU in the component's edit dialog.

#### Logs taken while reproducing problem
-

**Comment by cjelger** [comment]
By default, Magento only allows queries to fetch  "base" product and it is not possible to fetch variants. However, we always fetch the base product and its variants, so you don't have to do the changes you want. If you want to be able to choose a variant with the product picker, simply set the `filter` property to `folderOrProductOrVariant ` as explained in https://github.com/adobe/commerce-cif-connector#product-picker

This should solve your issue, please reopen if not.

**Comment by cjelger** [comment]
BTW, the product teaser is already configured like that by default so you shouldn't have to do anything, see https://github.com/adobe/aem-core-cif-components/blob/master/ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml#L37-L39
