### ISSUE TITLE
Validation errors with filevault-maven-plugin 1.1.4 in core-cif-components-apps-1.2.0.zip

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-cif-components#388]
When the core-cif-components-apps-1.2.0.zip content package is embedded into a project which is using the latest maven-filevault-plugin the build is throwing a validation error:
```[INFO] [ERROR] ValidationViolation: "jackrabbit-docviewparser: Invalid XML found: Given root node name 'cq:design_dialog' (implicitly given via filename) cannot be resolved. The prefix used in the filename must be declared as XML namespace in the child docview XML as well!", filePath=jcr_root/apps/testing-cif-cloud-vendor-packages/application/install/core-cif-components-apps-1.2.0.zip/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_design_dialog/.content.xml, nodePath=/apps/core/cif/components/commerce/productlist/v1/productlist/cq:design_dialog```

**Comment by vigneshwarant** [comment]
<skipValidation>true</skipValidation> needs to be added both the parent POM and module where the validation needs to be skipped.
