### ISSUE TITLE
Hard requirement of miniaccount-node

### ISSUE THREAD

**Issue by Tylopilus** [adobe/aem-core-cif-components#470]
https://github.com/adobe/aem-core-cif-components/blob/1279af685591212a13083c61104233d1f32c9d56/ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigation.html#L25

This line should be replaced with
`<div` `id="miniaccount"></div>`

This used to be the case but apparently a PR has overwritten this change.

**Comment by dplaton** [comment]
@Tylopilus The resource inclusion was implemented along with the `miniaccount` component in https://github.com/adobe/aem-core-cif-components/commit/4baa54e222eeeca8928db65d8351318450ecf087
