### ISSUE TITLE
Pagination Type is always set to default on Product List

### ISSUE THREAD

**Issue by znikolovski** [adobe/aem-core-cif-components#506]
This seems to be also related to the fact that the PageMetadata is the first instance where the product list is executed. The code in ProductCollectionImpl https://github.com/adobe/aem-core-cif-components/blob/f97436ba47497721faa284475219004f8bd2f6d8/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java#L82 is incorrectly picking up the currentStyle of the page rather than the product list component which then ends up setting the pagination to default.

Setting a `paginationType` property on the category page (manually, via crx/de) results in a correct behaviour.

**Comment by cjelger** [comment]
Thanks @znikolovski - we are aware of issues with the `PageMetadata` model and will fix this.

**Comment by cjelger** [comment]
Should be solved by https://github.com/adobe/aem-core-cif-components/pull/507

**Comment by cjelger** [comment]
@znikolovski Can you please check if you still have this issue now that #507 has been merged? You'd of course have to install the current `-SNAPSHOT` CIF components bundle. Thank you.

**Comment by cjelger** [comment]
@znikolovski I actually verified that #507 solves this issue. Please reopen if needed.
