### ISSUE TITLE
Full cart and checkout component

### ISSUE THREAD

**Issue by paulrohrbeck** [adobe/aem-core-cif-components#522]
### User Story
As a user, I want to be able to see the cart and checkout process as a standalone page (or pages) because that's what I'm used to from other e-commerce shops.

### Description & Motivation
* Online shoppers are not accustomed to using a "mini checkout" the way it's implemented with the CIF Components. They're used to seeing a full-page to go through the checkout process. 
* Having the checkout process on a separate template that's more minimal with fewer distractions may also help with conversions.

### Deliverables
Add a new "full checkout" component (potentially based on the existing mini-cart component) that can be dropped on a page on its own and guide the user through the checkout process. To allow for more flexibility and extensibility, there should also be a separate "full cart" component.

### Acceptance Criteria
* The full cart and full checkout components should have feature parity to the existing mini-cart component.
* The cart/checkout pages should be configurable similar to how the category/product/search pages are configurable.

**Comment by mhaack** [comment]
Thanks @paulrohrbeck this is actually planned for later 2021 (CIF-1465). (cc @martinbuergi )
