### ISSUE TITLE
CIF connecter vs core cif components version issues

### ISSUE THREAD

**Issue by praveenv2018** [adobe/aem-core-cif-components#523]
Hi,
CIF connector version 1.8.0-magento242ee is released and it is compatible with Magento 242 version. whereas Core cif components version 1.9 is released and it is not compatible with Magento 242 version. 1.9 version of CIF Core components are still using magento graphql version 6.0.0-magento235.
Could you please let us know when the CIF core components version is released which is compatible with magenot graph ql version 9.0.0-magento242ee.

**Comment by mhaack** [comment]
Hi @praveenv2018, 

> Could you please let us know when the CIF core components version is released which is compatible with magenot graph ql version 9.0.0-magento242ee.

Yes this is planned for this week.

**Comment by praveenv2018** [comment]
Hi
We have installed cif connector version 1.8.0-magento242ee. But after that, we have installed core cif components version 1.8 and 1.9 also. The bundle is not in an active state as the version mismatches in Magento graphql.
Core cif components 1.8 or 1.9 versions are using <magento.graphql.version>6.0.0-magento235</magento.graphql.version>.
where as CIF connector 1.8.0-magento242ee version using <magento.graphql.version>9.0.0-magento242ee</magento.graphql.version>,
I hope you understand the issue.

**Comment by mhaack** [comment]
@praveenv2018 please use the https://github.com/adobe/commerce-cif-connector/releases/tag/cif-connector-reactor-1.8.0 CIF Connector release, not the 1.8.0-magento242ee version.

**Comment by cjelger** [comment]
Note that CIF Connector `1.8.0` is compatible with Magento 2.4.2, older versions of the GraphQL library are usually "forward-compatible" and work with newer versions of Magento.

**Comment by praveenv2018** [comment]
Hi,
We do not have some of the core functionalities like wish list in cif connector 1.8 version.
https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-wishlist.html
As per the above documentation, some of the classes are not available in <magento.graphql.version>6.0.0-magento235

**Comment by cjelger** [comment]
The CIF components do not yet support `9.0.0-magento242ee`, this is going to be included in the next release, or you can use the current `-SNAPSHOT` version.

**Comment by praveenv2018** [comment]
Ok. Thanks for the information. Any idea when this release will happen?

**Comment by praveenv2018** [comment]
Ok. Thank you.
