### ISSUE TITLE
Button component doesn't use UrlProvider to create product and category links

### ISSUE THREAD

**Issue by paulrohrbeck** [adobe/aem-core-cif-components#553]
### Expected Behaviour
When using the [CIF Button (v1) component](https://github.com/adobe/aem-core-cif-components/tree/master/ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button), I expected it to create URLs that are formatted based on what's defined in the UrlProvider OSGi config.

Expected: /content/luma/language-masters/en/category/category-page.21.html/women/tops-women

### Actual Behaviour

The behavior that I'm seeing is that it's missing the suffix and therefore breaks the special sling mapping that's set up.

Actual: /content/luma/language-masters/en/category/category-page.21.html

#### Steps to Reproduce

Drop the CIF Button on a page and link to a category from the authoring dialog.

#### Platform and Version
AEM 6.5.6

#### Logs taken while reproducing problem
ButtonImpl:
```
    private String constructUrl(final String pagePath, final String urlKey) {
        return String.format("%s.%s.html", pagePath, urlKey);
    }
```

**Comment by mhaack** [comment]
Thanks for reporting, we will fix that.

(Internaly tracked via CIF-2049)
