### ISSUE TITLE
[Examples] Commerce section title and left margin are not aligned with the rest on aemcomponents.dev main page

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-core-cif-components#577]
![image](https://user-images.githubusercontent.com/3670963/119836716-9ed0e300-bf0a-11eb-9d66-03b1c511b684.png)

Title is missing separator and all section is off to the right a few pixels. This is due to direct usage of Core Components RTs, after https://github.com/adobe/aem-core-wcm-components/issues/1452 was fixed and released all examples should reference the proxies.

Possible fix: replace all direct usage of core components RTs (https://github.com/adobe/aem-core-cif-components/search?l=XML&q=%22core%2Fwcm%2Fcomponents%22) with the Library proxies.

**Comment by mhaack** [comment]
Tracked via CIF-2212
