### ISSUE TITLE
Some icons are not working with minified clientlibs

### ISSUE THREAD

**Issue by solojavier** [adobe/aem-core-cif-components#63]
### Expected Behaviour

All icons to show up. Specifically I've detected close icon and basket icon in cart.

```
.icon__root.icon__root-close {
    background: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>');
}
```

### Actual Behaviour

When minification is turned on: https://www.aemquickstart.in/2016/04/enable-js-and-css-minification.html

Then the css for some svg icons is not working

For instance, this doesn't work:

```
.icon__root.icon__root-close{background:url('data:image/svg+xml;utf8,<svgxmlns="http://www.w3.org/2000/svg"width="24"height="24"viewBox="002424"fill="none"stroke="currentColor"stroke-width="2"stroke-linecap="round"stroke-linejoin="round"><linex1="18"y1="6"x2="6"y2="18"></line><linex1="6"y1="6"x2="18"y2="18"></line></svg>')}
```

#### Steps to Reproduce

* Enable minification in AEM instance.
* Go to a `/content/venia/us/en/` page or any page that contains mini-cart component.
* Open the cart.
* Close icon is not showing.

#### Platform and Version

AEM 6.5

#### Sample Code that illustrates the problem

OOTB

#### Logs taken while reproducing problem

N/A

**Comment by daamdaam** [comment]
My fix, as recommended by a colleague, and its a fairly obvious one when you think about it, was to pass it thro a url encoder.

you can use something like meyerweb's one, or do i did - install a urlencoder/decoder in vscode.

this results in 

background: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>')

being converted to

background: url('data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22currentColor%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%3Cline%20x1%3D%2218%22%20y1%3D%226%22%20x2%3D%226%22%20y2%3D%2218%22%3E%3C%2Fline%3E%3Cline%20x1%3D%226%22%20y1%3D%226%22%20x2%3D%2218%22%20y2%3D%2218%22%3E%3C%2Fline%3E%3C%2Fsvg%3E')

You only need to convert the <svg> markup part, if you have multiple in the file to convert, then a bit of regex will be able to select the relevent bits.

I found saving this and re-enabling minification in the configMgr resulted in my SVGs still working.

This is a much nicer way then uploading SVGs to the DAM - i have 794 svgs in my LESS, uploading all that and maintaining it would have been a hassle, to say the least.

Let me know, assuming this is helpful, if you want more information on the extension/encoder i used.

thanks
