### ISSUE TITLE
Menu cache is flush not working as expected

### ISSUE THREAD

**Issue by frappierer** [adobe/aem-core-cif-components#646]
### Expected Behaviour
Changing a category name in Magento should be reflected in the AEM Menu after TTL has expired.

### Actual Behaviour
TTL is set to venia/components/commerce/navigation:true:5:300.
After changing the name in magento it changed in AEM, but it took about an hour.

#### Steps to Reproduce
* Use Venia OOTB
* Change category name in Magento
* Wait for TLL (eg. 5 min) as set in config
* Check in AEM if menu item name has changed.

#### Platform and Version
* CIF 2.0
* AEM as a cloud service
* Tested only on author instance

**Comment by LSantha** [comment]
@frappierer , the CIF navigation cache (or menu cache) is working as expected, including cache expiration on timeout. 
You can check this by configuring POST requests in the GraphQL client OSGi configuration to not have Graphql caching for your requests on the Magento side.
It's very likely that you have GraphQL caching enabled for Magento, which has a longer expiration time than what you configured for navigation.
