### ISSUE TITLE
Ability to include & exclude a category in commerce navigation

### ISSUE THREAD

**Issue by hsaifudeen** [adobe/aem-core-cif-components#665]
### User Story

As an author, I want to have the ability to include & exclude a commerce category in menu so that I can hide the category from users in the navigation. 

### Description & Motivation

Similar to the Magento FrontEnd, CIF needs the capability to make use of the Magento 'Include in Menu' option in the Commerce navigation component. May be this is represented in GraphQL via `include_in_menu` property. Commerce navigation component needs to respect this attribute.

### Deliverables

Commerce navigation component needs to consider the `include_in_menu` property of Magento

### Acceptance Criteria

When the author/backend developer turn on/off the 'Include in Menu' option in Magento backend, the commerce navigation should reflect accordingly.

### Verification Steps

1. Login to Magento backend
2. Go to any category
3. Turn off 'Include in Menu' option (default is On)
4. Check whether the Category gets disappeared in commerce navigation
5. Turn it on & check whether the category appears again

**Comment by mhaack** [comment]
@hsaifudeen thanks for reporting, the issue has been fixed and the fix will be included in the next release.

**Comment by hsaifudeen** [comment]
Thanks Markus, looking forward to try this in next release.
