### ISSUE TITLE
CategoryList GraphQL Query "category_uid" filter not working as expected for Core CIF Components Version 2.2.0

### ISSUE THREAD

**Issue by ChrisDiktakis** [adobe/aem-core-cif-components#707]
The category_uid filter is not working as expected.

When running the following query: 
{
  categoryList(
    filters: {
      category_uid: {in: ["2","3"]}
    }
  ) {
    children_count
    children {
      uid
    }
  }
}

I get the following response: 

{
    "errors": [
        {
            "message": "Value of uid \"'2'\" is incorrect.",
            "extensions": {
                "category": "graphql-input"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "categoryList"
            ]
        }
    ],
    "data": {
        "categoryList": null
    }
}

But when I change the **category_uid** filter to be **ids** as in the following request:

{
  categoryList(
    filters: {
      ids: {in: ["2","3"]}
    }
  ) {
    children_count
    children {
      uid
    }
  }
}

I get a correct response.

This affects the Core CIF Components Version 2.2.0. Specifically the CategoryCarousel and FeaturedCategoryList Components on AEM as a Cloud Service.

**Comment by paulrohrbeck** [comment]
Do you have UID Support enabled in the CIF Configuration? Then you would need to reauthor the components so that it's using the UID instead of numerical IDs (e.g. "Mg==" vs. "2").

**Comment by ChrisDiktakis** [comment]
@paulrohrbeck Thanks so much. That resolved my issue.
