### ISSUE TITLE
General question regarding GraphQl requests in Sling Models

### ISSUE THREAD

**Issue by ChrisDiktakis** [adobe/aem-core-cif-components#746]
Let's assume I wanted to transform data that I get from GraphQl in some way in the AEM backend in a SlingModel. How would I go about executing the query in the backend? I understand how to do it in the frontend through React components. Is it considered best practice to make graphQl requests in sling models?

**Comment by mhaack** [comment]
@ChrisDiktakis see here for example: https://github.com/adobe/aem-core-cif-components/tree/master/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser

Our pattern is the Sling Models use a retriever helper call and that uses the `MagentoGraphqlClient` to execute the GraphQL queries. The result can be returned as JSON objects or already mapped to concrete commerce Java models based on the GraphQL schema. See https://github.com/adobe/aem-core-cif-components/blob/master/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java

You can exten the `AbstractProductRetriever` or another working abstract retriever from https://github.com/adobe/aem-core-cif-components/tree/master/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever and provide your own query.
