### ISSUE TITLE
Wiki link not working

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-cif-components#825]
The link https://github.com/adobe/aem-core-cif-components/wiki used in the README (https://github.com/adobe/aem-core-cif-components#documentation) and also used externally e.g. in https://github.com/adobe/aem-cif-guides-venia#individual-product-and-category-page-urls does no longer work. Please either reenable the GitHub wiki or adjust the links to point to the new location.

**Comment by mhaack** [comment]
@adobe export issue to Jira project CIF

**Comment by kwin** [comment]
@Buuhuu Thanks Dirk for the quick fix, but I don't find the information formerly available at https://github.com/adobe/aem-core-cif-components/wiki/configuration#configuring-and-customising-product-and-category-pages-url (still linked from https://github.com/adobe/aem-cif-guides-venia#individual-product-and-category-page-urls). Where is the documentation regarding URL customization or product/category pages?

**Comment by Buuhuu** [comment]
Thanks for raising this. Would can find the information you are looking for probably here https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/content-and-commerce/storefront/administering/advanced-url-configuration.html?lang=en

**Comment by kwin** [comment]
@Buuhuu Thanks for the quick answer. Indeed this was the info I was looking for. I raised https://github.com/adobe/aem-cif-guides-venia/pull/256 to get the link fixed in Venia.
