### ISSUE TITLE
Button V2 CIF core component is not working : URL formed is incorrect

### ISSUE THREAD

**Issue by del27634** [adobe/aem-core-cif-components#875]
### Expected Behaviour
The URL for selected product in buttion component should have product SKU and product name in the URL. 
### Actual Behaviour
The URL formed doesn't have value for SKU parameter and instead of the actual SKU string placeholder {{sku}} is added.
e.g. https://author-domain/content/my_content/product-page.html/{{sku}}/product_name.html
#### Steps to Reproduce
1. author CIF button (v2) component
2. select link type as **product** from the dropdown
3. Author any product from product selector
4. save dialog
5. View in publish, inspect the link.
#### Platform and Version
1. AEMaaCS (2022.3.6582.20220307T234020Z-220100)
2. core cif components from version 2.5.0 onwards.

#### Sample Code that illustrates the problem
1. https://github.com/adobe/aem-core-cif-components/commit/ecd5e54e15942fee30be074d4d64332721c8d066#r70383760

Please check the above link, have described the issue root cause.

#### Logs taken while reproducing problem

**Comment by Buuhuu** [comment]
Fixed since 2.7.2
