### ISSUE TITLE
URL Provider Update - Allow for querying category by URL Path

### ISSUE THREAD

**Issue by pmichelotti** [adobe/aem-core-cif-components#886]
---
name: Allow for querying category by URL Path
about: URL Provider
---

### User Story
As a site manager I want to be able to set category ID lookup to be based off URL Path so that categories with matching URL keys can be looked up uniquely

### Description & Motivation
In large enough catalog taxonomies it is fairly common for URL keys to match between categories.  The current URL Provider implementation uses URL Key to look up the ID of a category which causes effectively indeterminate behavior when there are categories with matching URL Keys (see https://github.com/adobe/aem-core-cif-components/blob/master/bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java#L451).  

### Deliverables
Code change needed to update the URL Provider to know whether to use URL Key or URL Path to query for category IDs.

### Acceptance Criteria
* I am able to set in the configuration of the URL Provider whether URL Path or URL Key or ID should be used to identify categories
* Given that I am viewing two categories with matching URL Keys but different URL Paths and that I have configured the URL Provider to lookup categories by URL Path and to render URL Paths in the URL then I see the expected category content in each category I am viewing

### Verification Steps
* Setup multiple categories in Magento with the same URL key at different places in a taxonomy so the URL path is differing
* Configure the URL provider to user URL path to lookup category ID
* Open category pages for both categories and make sure the content matches what is expected based on the category definitions in Magento

**Comment by Buuhuu** [comment]
@adobe export issue to Jira project CIF

**Comment by Buuhuu** [comment]
Released with CIF Core Components 2.9.0
