### ISSUE TITLE
Add a CIF Page v3 which extends the Core Component Page v3

### ISSUE THREAD

**Issue by rubnig** [adobe/aem-core-cif-components#902]
### User Story
As an author, I want to be able to use the _featured image_ functionality from the Core Components Page v3 component, in a Core CIF Page.

### Description & Motivation
This is currently not possible, as the Core CIF Page extends the v2 Core Component Page (core/wcm/components/page/v2/page) [current-page-impl](https://github.com/adobe/aem-core-cif-components/blob/master/ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/.content.xml)

### Deliverables
Add a new Page Component in the CIF package that extends the Core Page v3 Component and make sure that the Page Model and possible Servlets and Filters take this new v3 resource type into account.

### Acceptance Criteria
- Everywhere a CIF Page is used, the new v3 Page should work as well (Component, Sling Model, Servlet, Filter, ...)
- All new Core Page Component v3 functionality works as well for the CIF Page (for example the _featured image_ functionality)

### Verification Steps
- Create a new Page (based on the new Core CIF Page v3 component)
- Verify if all CIF functionality still works as expected
- Verify that new Core Page Component v3 functionality also works with the new Core CIF v3 Page Component

**Comment by Buuhuu** [comment]
Released in CIF 2.9.0
