### ISSUE TITLE
AEM CIF Core Components - Core Bundle - Installed state

### ISSUE THREAD

**Issue by pranav08052017** [adobe/aem-core-cif-components#965]
### Expected Behaviour
We deployed AEM CIF core 2.12 version but bundle not in active state
Error:
**com.adobe.cq.cif.common.associatedcontent,version=[1.0,2) -- Cannot be resolved**
### Actual Behaviour
It should be active state
### Reproduce Scenario (including but not limited to)
Deploy AEM CIF core components package via maven dependency
#### Platform and Version
AEM 6.5 , Service pack 6.5.12
#### Logs taken while reproducing problem
<img width="713" alt="Error" src="https://user-images.githubusercontent.com/115392162/194742984-20a75ace-e7f9-4f10-8a11-adc3b928bd3f.png">

**Comment by herzog31** [comment]
Please check https://github.com/adobe/aem-core-cif-components#system-requirements and install the minimum required version of the CIF Add-on which provides the `com.adobe.cq.cif.common.associatedcontent` package.
