### ISSUE TITLE
ProductDetails and Productlist Components not loading products

### ISSUE THREAD

**Issue by swativ0755** [adobe/aem-core-cif-components#974]
Expected Behaviour
 Products and Categories should be loaded as per the default implementation.

Actual Behaviour
On load of ProductDetails and productlist component receiving "No Products to display" error. After debugging the issue found like,
From CIF 2.0.0 the support for "id" was removed and replaced with "uid". And UID's got introduced in Adobe Commerce 2.4.2 but we are on 2.4.1. As we are using CIF latest version(2.11.0), GraphQL queries are generated with the filter attributes like category_uid, uid etc. As this attribute is not supported in 2.4.1 commerce. Because of the above attributes, GraphQL query is returning error response. Due to this error both productDetails and productlist components displaying error message "No Products to display".

Category Query :
Filter Attributes: category_uid, uid , staged

PRODUCT QUERY :
Filter Attributes:  uid, color

Reproduce Scenario (including but not limited to)
Steps to Reproduce
1. AEM instance with SP12 and commerce addon "aem-commerce-addon-65-2022.09.30.00". 
2. Configure the magento endpoint which is on 2.4.1
3. Include prodctdetails or productlist components on the page and the view as published.

Platform and Version
AEM 6.5.12 and CIF 2.11.0 and adobe commerce 2.4.1

Sample Query Generated:

{categoryList(filters:{category_uid:{eq:"73"}}){uid,description,name,image,product_count,meta_description,meta_keywords,meta_title,url_key,url_path,children{id,uid,url_key,url_path},staged}}

Query that works:

{categoryList(filters:{ids:{eq:"73"}}){description,name,image,product_count,meta_description,meta_keywords,meta_title,url_key,url_path,children{id,url_key,url_path}}}

**Comment by herzog31** [comment]
Hi @swativ0755, please have a look at https://github.com/adobe/aem-core-cif-components/blob/master/VERSIONS.md. The CIF Core Components version you are using requires Adobe Commerce 2.4.2 or higher. So the behaviour you're describing is working as intended.
